_BASE_: "Base-SSIS.yaml"
MODEL:
  WEIGHTS: "./output/SSISv2_MS_R_101_bifpn_with_offset_class_maskiouv2_da_bl/model_ssisv2_final.pth"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  RESNETS:
    DEPTH: 101
  FCOS:
    NUM_CLASSES: 2
    OFFSET: True
    CLASS_AWARE: True
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NORM: "SyncBN"
  CONDINST:
    MASK_OUT_STRIDE: 2
    MAX_PROPOSALS: 450
    MASK_HEAD:
      CHANNELS: 8
      DEFORM_MASKIOU: True
      BOUNDARY_LOSS: True    
SOLVER:
  STEPS: (40000,)
  MAX_ITER: 45000
  BASE_LR: 0.001
  IMS_PER_BATCH: 2
DATASETS:
  TRAIN: ("soba_cast_shadow_train_full",)
  TEST: ("soba_cast_shadow_val_full",)
OUTPUT_DIR: "output/SSIS_MS_R_101_bifpn_with_offset_class"
